In [79]:
#https://github.com/SrinidhiRaghavan/AI-Sentiment-Analysis-on-IMDB-Dataset/blob/master/driver_3.py

In [80]:
import pandas as pd

In [81]:
imdbData = pd.read_csv("C://Users/583175/.jupyter/imdb_tr.csv", header=0, encoding = 'ISO-8859-1')

In [82]:
reviews = imdbData['text']

In [84]:
reviews

0        first think another Disney movie, might good, ...
1        Put aside Dr. House repeat missed, Desperate H...
2        big fan Stephen King's work, film made even gr...
3        watched horrid thing TV. Needless say one movi...
4        truly enjoyed film. acting terrific plot. Jeff...
5        memory "The Last Hunt" stuck since saw 1956 13...
6        Shakespeare fan, appreciate Ken Branagh done b...
7        privilege watching Scarface big screen beautif...
8        real classic. shipload sailors trying get town...
9        Serials short subjects originally shown theate...
10       strange sex comedy there`s little comedy whole...
11       many problems film, worst continuity; re-editi...
12       Rosie wasted lot TV time talking Tainos super ...
13       Man, people got chill. movie artistic genius. ...
14       great movie could Soylent Green. scenes people...
15       Wonderful family drama/comedy starring MacClai...
16       "Ko tamo peva" one best films ever saw. tragic.

In [128]:
reviews[1]

'Put aside Dr. House repeat missed, Desperate Housewives (new) watch one. don\'t know exactly plagued movie. never thought I\'d say this, want 15 minutes fame back.<br /><br />Script, Direction, can\'t say. recognized stable actors (the usual suspects), thought Herbert Marshall class addition sat good cheesy flick. Boy, wrong. Dullsville.<br /><br />My favorite parts: "office girl" makes 029 keypunch puts cards 087 sorter. LOL @ "the computer". I\'d like someone identify next device - 477 ? It\'s even dinosaur\'s time.<br /><br />And dinosaurs don\'t much time waste.'

In [139]:
import re

In [145]:
REPLACE_NO_SPACE = re.compile("(\.)|(\;)|(\:)|(\!)|(\')|(\?)|(\,)|(\")|(\()|(\))|(\[)|(\])|(\d+)")

In [146]:
NO_SPACE = ""

In [165]:
preProcessedText = REPLACE_NO_SPACE.sub(NO_SPACE, "Hello, My name is John. I'm working in google.")

In [166]:
print(preProcessedText)

Hello My name is John Im working in google


In [85]:
polarity = imdbData['polarity']

In [86]:
polarity

0        1
1        0
2        1
3        0
4        1
5        1
6        0
7        1
8        1
9        1
10       0
11       0
12       0
13       1
14       1
15       1
16       1
17       1
18       1
19       1
20       0
21       1
22       1
23       1
24       0
25       0
26       0
27       1
28       0
29       0
        ..
24970    1
24971    1
24972    0
24973    1
24974    0
24975    0
24976    1
24977    0
24978    1
24979    0
24980    0
24981    1
24982    1
24983    0
24984    1
24985    1
24986    1
24987    0
24988    1
24989    1
24990    1
24991    1
24992    0
24993    1
24994    0
24995    0
24996    1
24997    0
24998    0
24999    1
Name: polarity, Length: 25000, dtype: int64

In [87]:
import sklearn

In [88]:
from sklearn.model_selection import train_test_split

In [89]:
features = reviews
labels = polarity

In [90]:
train, test, train_labels, test_labels = train_test_split(features,
                                                          labels,
                                                          test_size=0.10,
                                                          random_state=42)

In [92]:
from sklearn.feature_extraction.text import CountVectorizer

In [102]:
vectorizer = CountVectorizer()
vectorizerTr = vectorizer.fit(train)
vectorizerTe = vectorizer.fit(test)

In [103]:
trainMatrix = vectorizerTr.transform(train)
testMatrix = vectorizerTe.transform(test)

In [104]:
trainMatrix

<22500x28404 sparse matrix of type '<class 'numpy.int64'>'
	with 2273780 stored elements in Compressed Sparse Row format>

In [105]:
testMatrix

<2500x28404 sparse matrix of type '<class 'numpy.int64'>'
	with 265260 stored elements in Compressed Sparse Row format>

In [106]:
print(vectorizer.get_feature_names)
#print(trainMatrix.toarray())

<bound method CountVectorizer.get_feature_names of CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)>


In [107]:
from sklearn.linear_model import SGDClassifier

In [108]:
clf = SGDClassifier(loss="hinge", penalty="l1", max_iter=20)

In [109]:
clf.fit(trainMatrix, train_labels)

SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', max_iter=20, n_iter=None,
       n_jobs=1, penalty='l1', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=0, warm_start=False)

In [112]:
train_labels

4484     0
11558    1
16900    1
8936     0
10782    0
23277    0
2412     0
7247     0
6777     1
15601    1
24459    1
2425     0
16983    1
10356    0
15429    1
24683    0
13469    0
9893     1
9279     1
5215     0
14944    0
1215     1
9757     0
5339     0
5456     1
17300    1
18478    0
3426     0
606      1
23250    1
        ..
24233    1
18942    1
8666     1
6396     1
19769    0
20939    0
17568    0
6420     1
5051     1
5311     1
2433     1
23333    0
769      1
1685     1
8322     1
16023    0
11363    1
14423    1
21962    1
4426     1
16850    0
6265     1
22118    1
11284    1
11964    1
21575    1
5390     0
860      0
15795    1
23654    1
Name: polarity, Length: 22500, dtype: int64

In [113]:
test_labels

6868     1
24016    0
9668     1
13640    0
14018    0
7488     1
5804     1
12909    0
3386     0
9567     0
21423    1
3503     0
6657     0
19192    1
2518     1
13361    0
21135    0
21080    0
6492     1
6891     0
7752     0
8614     0
6649     1
2227     0
12060    0
19122    0
9622     1
12279    0
16447    0
423      1
        ..
2492     0
742      1
24144    1
17349    0
20163    0
23783    1
17281    0
17978    1
3073     1
20905    1
1393     0
14395    1
7191     1
16946    1
15903    0
7606     1
19148    0
20011    1
19852    0
15907    0
907      1
22650    0
7917     1
4104     1
18824    0
20854    1
15308    1
13238    1
21567    1
11393    0
Name: polarity, Length: 2500, dtype: int64

In [116]:
testOutput = clf.predict(testMatrix)

In [123]:
testOutput

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [119]:
from sklearn.metrics import accuracy_score

In [120]:
accuracy = accuracy_score(testOutput, test_labels)

In [121]:
accuracy

0.85519999999999996

In [167]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [168]:
confMatrix = confusion_matrix(testOutput, test_labels)

In [172]:
print(confMatrix)

[[1096  184]
 [ 178 1042]]


In [170]:
clfReport = classification_report(testOutput, test_labels)

In [173]:
print(clfReport)

             precision    recall  f1-score   support

          0       0.86      0.86      0.86      1280
          1       0.85      0.85      0.85      1220

avg / total       0.86      0.86      0.86      2500



In [124]:
negReview = "The movie was really boring and I hate it"
posReview = "The movie was great and I loved it. Everyone should watch it"
bothReviews = ["The movie was really boring and I hate it", 
               "The movie was great and I loved it. Everyone should watch it",
              "The second part of the movie was not interesting as it was in the first part."]

posReview = [posReview]
negReview = [negReview]

In [125]:
posReviewMatrix = vectorizer.transform(posReview)
negReviewMatrix = vectorizer.transform(negReview)
bothReviewMatrix = vectorizer.transform(bothReviews)

In [126]:
sentimentOutput = clf.predict(bothReviewMatrix)

In [127]:
print(sentimentOutput)

[0 1 0]
